name: CI

on:
  push:
    branches: [ refactor-cictl ]
  pull_request:
    branches: [ refactor-cictl ]

env:
  PROJECT_NAME: zint  

jobs:
  fuzz_ean_fuzzer:
    runs-on: ubuntu-latest
    steps:
      - id: start-fuzzing
        name: Build and Instrument
        uses: CodeIntelligenceTesting/github-actions/start-fuzzing@refactor-cictl
        with:
          ci_fuzz_api_token: ${{ secrets.CI_FUZZ_DEV_API_TOKEN }}
          project: ${{ env.PROJECT_NAME }}
          test_collection: "projects/zint-a3712029fa824b11/campaigns/ean_fuzzer-f5b69279"
          git_reference: ${{ github.sha }}          
          fuzzing_server_address: grpc-api.demo.code-intelligence.com:443
      - id: monitor-fuzzing
        name: Fuzzing
        uses: CodeIntelligenceTesting/github-actions/monitor-fuzzing@refactor-cictl
        with:
          ci_fuzz_api_token: ${{ secrets.CI_FUZZ_DEV_API_TOKEN }}
          project: ${{ env.PROJECT_NAME }}
          test_collection_run: ${{ steps.start-fuzzing.outputs.test_collection_run }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_request_number: ${{ github.event.pull_request.number }}
          owner: ${{ github.event.repository.owner.login }}
          repository: ${{ github.event.repository.name }}
          timeout: 60
          fuzzing_server_address: grpc-api.demo.code-intelligence.com:443
          dashboard_address: https://app.demo.code-intelligence.com
      - id: report-coverage
        name: Report Coverage
        uses: CodeIntelligenceTesting/github-actions/report-coverage@refactor-cictl
        if: ${{ github.event_name == 'pull_request' && (success() || failure()) }}
        with:
          ci_fuzz_api_token: ${{ secrets.CI_FUZZ_DEV_API_TOKEN }}
          project: ${{ env.PROJECT_NAME }}
          test_collection_run: ${{ steps.start-fuzzing.outputs.test_collection_run }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_request_number: ${{ github.event.pull_request.number }}
          owner: ${{ github.event.repository.owner.login }}
          repository: ${{ github.event.repository.name }}
          git_reference: ${{ github.sha }}
          fuzzing_server_address: grpc-api.demo.code-intelligence.com:443          
          dashboard_address: https://app.demo.code-intelligence.com
